### ISSUE TITLE
Ambiguity in the pie chart

### ISSUE THREAD

**Issue by masoom80** [app-generator/django-dynamic-charts-tests#2]
The instructions say "localhost:8000/dyn-chart/sales/pie/country/20/ - PIE chart for Country sales, in the last 20 days"
Should the chart be about the number of sales in the last 20 days in each country?like this one:{us:20 , can:30 ,brz:40}

**Comment by app-generator** [comment]
Hello @masoom80 

Yes, this is correct `us:20 , can:30 ,brz:40}`
